### ISSUE TITLE
Navigation bar not customized in transition

### ISSUE THREAD

**Issue by shmidt** [adamdebono/ADFlipTransition#1]
Hi, thanks for the amazing code!

Trying to integrate into my project,
and if there is navigation bar, it shows in transition without theme ( I use UIAppearance).
Is it possible to do something with it?
P.S. I attached pics for better understanding.
![ios simulator screen shot sep 4 2013 8 47 50 pm](https://f.cloud.github.com/assets/1472370/1082139/5b466332-1583-11e3-9781-39d9fc33777f.png)
![ios simulator screen shot sep 4 2013 8 47 57 pm](https://f.cloud.github.com/assets/1472370/1082141/5fa9d3c8-1583-11e3-8611-58f1f3c6d83e.png)

**Comment by adamdebono** [comment]
That's a weird one. I'd say it's probably got something to do with offscreen rendering. There's probably a call I'm not doing which loads the UIAppearance stuff. Something like `layoutSubviews` or `setNeedsDisplay:`.

**Comment by shmidt** [comment]
@adamdebono Thanks, I'll try it out.

**Comment by shmidt** [comment]
I just made the tint of navbar approximately same color as used in theme.
