### ISSUE TITLE
it doesnt fill the whole screen

### ISSUE THREAD

**Issue by uzman** [adamdebono/ADFlipTransition#4]
hi,
there is a bug in your sample in the first tab.
first rotate the ipad to landscape, then hit the Flip as Child buttton.
it doesn't fill the whole screen. there is a gap on the right (256px).
- when the ipad rotates the child view is not centered in landscape mode.

thanks...

**Comment by adamdebono** [comment]
That's how it should be. If you look in the code, the function is called with a size of `(350, 350)`.

**Comment by uzman** [comment]
yes, it open the view in size of 350,350.
try this; (iOS 6.1)
-run the app in portrait mode
-hit flip as child
-rotate the iPad
-you will see what i mean. shadowView doesnt fill the whole screen.

**Comment by adamdebono** [comment]
adamdebono/ADFlipTransition@ 24a78b3835261cf1d6db0ba56c52f7ffd4d58673
