### ISSUE TITLE
The podspec file is invalid

### ISSUE THREAD

**Issue by jeraldj** [adamdebono/ADFlipTransition#7]
pod 'ADFlipTransition', :git => 'https://github.com/adamdebono/ADFlipTransition.git', :branch => 'master'

```

### Error

```

Pod::DSLError - Invalid `ADFlipTransition.podspec` file: /Users/jeraldj/Projects/calamity-gym-ios/Pods/Local Podspecs/ADFlipTransition.podspec:11: syntax error, unexpected tSYMBEG, expecting '}'
        :tag => '0.9.1'
         ^

**Comment by dmauer** [comment]
It just needs a comma after the "git:" line in the "source" section, e.g.:

<pre>
       s.source = {
                :git => 'https://github.com/adamdebono/ADFlipTransition.git',
                :tag => '0.9.1'
        }
</pre>

... trivial fix.
